/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type Codec,
  type Decoder,
  type EncodedAccount,
  type Encoder,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type MaybeAccount,
  type MaybeEncodedAccount,
} from '@solana/kit';

export const LIST_CONFIG_DISCRIMINATOR = 1;

export function getListConfigDiscriminatorBytes() {
  return getU8Encoder().encode(LIST_CONFIG_DISCRIMINATOR);
}

export type ListConfig = {
  discriminator: number;
  authority: Address;
  seed: Address;
  walletsCount: bigint;
  mode: number;
};

export type ListConfigArgs = {
  authority: Address;
  seed: Address;
  walletsCount: number | bigint;
  mode: number;
};

export function getListConfigEncoder(): Encoder<ListConfigArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', getU8Encoder()],
      ['authority', getAddressEncoder()],
      ['seed', getAddressEncoder()],
      ['walletsCount', getU64Encoder()],
      ['mode', getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: LIST_CONFIG_DISCRIMINATOR })
  );
}

export function getListConfigDecoder(): Decoder<ListConfig> {
  return getStructDecoder([
    ['discriminator', getU8Decoder()],
    ['authority', getAddressDecoder()],
    ['seed', getAddressDecoder()],
    ['walletsCount', getU64Decoder()],
    ['mode', getU8Decoder()],
  ]);
}

export function getListConfigCodec(): Codec<ListConfigArgs, ListConfig> {
  return combineCodec(getListConfigEncoder(), getListConfigDecoder());
}

export function decodeListConfig<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>
): Account<ListConfig, TAddress>;
export function decodeListConfig<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<ListConfig, TAddress>;
export function decodeListConfig<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
): Account<ListConfig, TAddress> | MaybeAccount<ListConfig, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getListConfigDecoder()
  );
}

export async function fetchListConfig<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<ListConfig, TAddress>> {
  const maybeAccount = await fetchMaybeListConfig(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeListConfig<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<ListConfig, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeListConfig(maybeAccount);
}

export async function fetchAllListConfig(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<ListConfig>[]> {
  const maybeAccounts = await fetchAllMaybeListConfig(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeListConfig(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<ListConfig>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeListConfig(maybeAccount));
}

export function getListConfigSize(): number {
  return 74;
}
