/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

export * from './addWallet';
export * from './freeze';
export * from './freezePermissionless';
export * from './initList';
export * from './removeWallet';
export * from './setupExtraMetas';
export * from './thaw';
export * from './thawPermissionless';
export * from './togglePermissionlessInstructions';
