[package]
name = "allow-block-list-client"
version = "0.1.0"
edition = "2021"

[lib]
name = "allow_block_list_client"

[dependencies]
solana-program = "2.2.1"
kaigan = ">=0.2.6"
borsh = "^0.10"
num-derive = "0.4.2"
num-traits = "0.2.19"